### ISSUE TITLE
docs: api documentation generation is not coherent

### ISSUE THREAD

**Issue by t1agob** [awslabs/aws-lambda-powertools-dotnet#105]
**What were you initially searching for in the docs?**
nothing specific. Just browsing through the API docs and looks like there are some classes that are exposed but not everything. Looking into the code looks like it's only generating docs for public classes and methods - which is fine - as long as it is coherent. 

Example: IXrayRecorder is generated for Tracing.Internal namespace but the actual implementation is not.

**Is this related to an existing part of the documentation? Please share a link**
https://sturdy-umbrella-97433f53.pages.github.io/api/api/AWS.Lambda.Powertools.Tracing.Internal.IXRayRecorder.html is an example but there might be others.

**Describe how we could make it clearer**
Make it coherent across utilities.

**If you have a proposed update, please share it here**
Decide whether to expose only classes and APIs to be used by end customers (developers) or expose everything since the code is all open source either way.

**Comment by sliedig** [comment]
Thanks for raising this. We are evaluating api docs and will review this. If this remains an issue please reopen. Thanks.
