### ISSUE TITLE
Bug: Dockerfile has RUN if statement that refers to SAM_BUILD_MODE = debug twice

### ISSUE THREAD

**Issue by kknd4eva** [awslabs/aws-lambda-powertools-dotnet#145]
### Expected Behaviour

Dockerfile in PowertoolsLoggingExample .NET solution has the following lines:

`# Build and Copy artifacts depending on build mode.
RUN mkdir -p build_artifacts
RUN if [ "$SAM_BUILD_MODE" = "debug" ]; then dotnet lambda package --configuration Debug; else dotnet lambda package --configuration Release; fi
RUN if [ "$SAM_BUILD_MODE" = "debug" ]; then cp -r /build/bin/Debug/net6.0/publish/* /build/build_artifacts; else cp -r /build/bin/Release/net6.0/publish/* /build/build_artifacts; fi
`

I think it should be (possibly) SAM_BUILD_MODE = "release" for the second if statement? 

### Current Behaviour

`# Build and Copy artifacts depending on build mode.
RUN mkdir -p build_artifacts
RUN if [ "$SAM_BUILD_MODE" = "debug" ]; then dotnet lambda package --configuration Debug; else dotnet lambda package --configuration Release; fi
RUN if [ "$SAM_BUILD_MODE" = "debug" ]; then cp -r /build/bin/Debug/net6.0/publish/* /build/build_artifacts; else cp -r /build/bin/Release/net6.0/publish/* /build/build_artifacts; fi
`

### Code snippet

```csharp
`# Build and Copy artifacts depending on build mode.
RUN mkdir -p build_artifacts
RUN if [ "$SAM_BUILD_MODE" = "debug" ]; then dotnet lambda package --configuration Debug; else dotnet lambda package --configuration Release; fi
RUN if [ "$SAM_BUILD_MODE" = "debug" ]; then cp -r /build/bin/Debug/net6.0/publish/* /build/build_artifacts; else cp -r /build/bin/Release/net6.0/publish/* /build/build_artifacts; fi
`
```

### Possible Solution

`# Build and Copy artifacts depending on build mode.
RUN mkdir -p build_artifacts
RUN if [ "$SAM_BUILD_MODE" = "debug" ]; then dotnet lambda package --configuration Debug; else dotnet lambda package --configuration Release; fi
RUN if [ "$SAM_BUILD_MODE" = "release" ]; then cp -r /build/bin/Debug/net6.0/publish/* /build/build_artifacts; else cp -r /build/bin/Release/net6.0/publish/* /build/build_artifacts; fi
`

### Steps to Reproduce

* Clone the current repository
* Open the PowertoolsLoggingExample solution in Visual Studio
* Examine the Dockerfile

### AWS Lambda Powertools for .NET version

latest

### AWS Lambda function runtime

dotnet6

**Comment by sliedig** [comment]
Hello @kknd4eva thank you for raising the first issue for this repo since it went public! 😄 

Debug is listed twice because we are using 2 sepeate conditional statements using parameter you set in the `template-docker.yaml` 

1. to determine what build configuration you want to execute
2. where to copy the output from.   

```
      DockerBuildArgs:
        SAM_BUILD_MODE: run # debug or run
```

If you set this flag to anything but `debug` the project will be built using `Release` configuration.

**Comment by kknd4eva** [comment]
Got it! Thank you, sorry for raising a red herring. I've also posted on LinkedIn to share that theses tools are out  (I think you liked my post?)- VERY exciting for the .NET world. I'm currently testing out the samples and will do a write up. :).

**Comment by sliedig** [comment]
Awesome! Thank you! Please let us know what you think. Any feedback welcome!
