### ISSUE TITLE
Metrics static instances makes testing hard

### ISSUE THREAD

**Issue by jakejscott** [awslabs/aws-lambda-powertools-dotnet#153]
### Expected Behaviour

We have a test project which references functions defined in their own projects/dlls. There seems to be issues with the static instances within the Metrics class.

We have forked the project and provided a sample program which causes a null reference exception. 

The `if (_instance != null) return;` check means that the following lines do not run:

```csharp
_instance = this;
_powertoolsConfigurations = powertoolsConfigurations;
_raiseOnEmptyMetrics = raiseOnEmptyMetrics;
_context = InitializeContext(nameSpace, service, null);
```

https://github.com/awslabs/aws-lambda-powertools-dotnet/blob/develop/libraries/src/AWS.Lambda.Powertools.Metrics/Metrics.cs#L61

I think that getting rid of the `AspectInjector` would simplify this project a lot. If the focus was on providing a library that does logging / metrics without all the magic we can choose how we want to use it ourselves.

I think the use of statics instances within the library makes thread safety a bit of a concern too.

### Current Behaviour

N/A

### Code snippet

```csharp
https://github.com/jakejscott/aws-lambda-powertools-dotnet/blob/bug/metrics-issues/libraries/examples/AWS.Lambda.Powertools.Examples.MetricsFunction/Program.cs
```

### Steps to Reproduce

https://github.com/jakejscott/aws-lambda-powertools-dotnet/blob/bug/metrics-issues/libraries/examples/AWS.Lambda.Powertools.Examples.MetricsFunction/Program.cs

### AWS Lambda Powertools for .NET version

latest

### AWS Lambda function runtime

dotnet6

**Comment by hjgraca** [comment]
Hey @jakejscott thanks for your feedback. After careful considerations we have agreed to keep using AspectInjector and Singleton patterns throughout the project. This approach is very useful to decorate the handlers not just for logging and metrics, but all other utilities in the project. We have also address many issues regarding exception handling and the particular case you describe should have been addressed. Again thanks for your feedback. Closing the issue.
