### ISSUE TITLE
Feature request: Functionality of Logger static class through dependency injection

### ISSUE THREAD

**Issue by NinovanderMark** [awslabs/aws-lambda-powertools-dotnet#161]
### Use case

It is currently difficult to test functions that depend on the static `Logger`, as we cannot provide an alternate or mock implementation.

Additionally, if we want to use the functionality that it offers for existing applications, we would have to replace all existing references to an implementation for ILogger<T> with the static `Logger` instance.

### Solution/User Experience

Instead of having to use the new Logger static class to perform logging, we would prefer to be able to inject it as an implementation of ILogger<T> and set it up through dependency injection.

This would be the idiomatic approach to supply a logger implementation in C#/.NET

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-dotnet/tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by amirkaws** [comment]
Hi @NinovanderMark, 

Thanks for the raising this feature request. The Logger is currently implemented according to the logger implementation in C#/.NET

You can creates an instance of Microsoft.Extensions.Logging.ILogger using following methods and inject it to your constructor for example: 

ILogger logger = Logger.Create<T>();
ILogger logger  = Logger.Create(string categoryName);

I hope it answers your question, please let me know if the feature you are asking is different.

**Comment by amirkaws** [comment]
Close the issue as it's been answered.
