### ISSUE TITLE
Docs: Metrics Adding Metadata sample incorrectly rendering

### ISSUE THREAD

**Issue by sliedig** [awslabs/aws-lambda-powertools-dotnet#165]
### What were you searching in the docs?

Adding metadata code sample incorrectly rendering

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-dotnet/core/metrics/#adding-metadata

### How can we improve?

```markdown
Fix tabs
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by amirkaws** [comment]
Released [v0.0.2-preview](https://github.com/awslabs/aws-lambda-powertools-dotnet/releases/tag/v0.0.2-preview).
