### ISSUE TITLE
Bug: bump nuget package versions

### ISSUE THREAD

**Issue by sliedig** [awslabs/aws-lambda-powertools-dotnet#177]
### Expected Behaviour

Update all nuget package versions to latest releases

### Current Behaviour

NA

### Code snippet

```csharp
NA
```

### Steps to Reproduce

NA

### AWS Lambda Powertools for .NET version

latest

### AWS Lambda function runtime

dotnet6

**Comment by amirkaws** [comment]
Released [v0.0.2-preview](https://github.com/awslabs/aws-lambda-powertools-dotnet/releases/tag/v0.0.2-preview).
