### ISSUE TITLE
chore: depreciation error for build

### ISSUE THREAD

**Issue by sliedig** [awslabs/aws-lambda-powertools-dotnet#180]
### Expected Behaviour

Build fails without error

### Current Behaviour

Build fails with error `Node.js 12 actions are deprecated.`
https://github.com/awslabs/aws-lambda-powertools-dotnet/actions/runs/3838020942

### Code snippet

```csharp
N/A
```

### Steps to Reproduce

N/A

### AWS Lambda Powertools for .NET version

latest

### AWS Lambda function runtime

dotnet6

**Comment by amirkaws** [comment]
Released [v0.0.2-preview](https://github.com/awslabs/aws-lambda-powertools-dotnet/releases/tag/v0.0.2-preview).
