### ISSUE TITLE
Feature: Templates for dotnet new and Visual Studio

### ISSUE THREAD

**Issue by hjgraca** [awslabs/aws-lambda-powertools-dotnet#198]
### Use case

We aim to be present were all .NET developers are and make it easy for developers to get started with Lambda Powertools. Having a dotnet new template and Visual Studio project templates will improve .NET developer experience.
Leverage AWS Toolkit for Visual Studio https://aws.amazon.com/visualstudio/ for distribution

### Solution/User Experience

Add new templates to [Amazon.Lambda.Templates](https://www.nuget.org/packages/Amazon.Lambda.Templates/)

## Creating Projects from "dotnet new"

The blueprints can be installed into the dotnet CLI by running the following command:

`dotnet new -i Amazon.Lambda.Templates::*`

Once that is complete the list of available projects types can be seen by running the following command. Including the Lambda Powertools templates.

`dotnet new -all`

<pre><code>
Templates                            Short Name                    Language      Tags
------------------------------------------------------------------------------------------------------
Lambda Detect Image Labels           lambda.DetectImageLabels      [C#]          AWS/Lambda/Function
Lambda Empty Function                lambda.EmptyFunction          [C#]          AWS/Lambda/Function
<b>Lambda Empty Function Powertools     lambda.EmptyFunction.Powertools  [C#]       AWS/Lambda/Function</b> 
Lambda Simple DynamoDB Function      lambda.DynamoDB               [C#]          AWS/Lambda/Function
<b>Lambda Simple DynamoDB Function Powertools      lambda.DynamoDB.Powertools    [C#]    AWS/Lambda/Function</b> 
Lambda Simple Kinesis Function       lambda.Kinesis                [C#]          AWS/Lambda/Function
Lambda Simple S3 Function            lambda.S3                     [C#]          AWS/Lambda/Function
Lambda ASP.NET Core Web API          lambda.AspNetCoreWebAPI       [C#]          AWS/Lambda/Serverless
Lambda DynamoDB Blog API             lambda.DynamoDBBlogAPI        [C#]          AWS/Lambda/Serverless
Lambda Empty Serverless              lambda.EmptyServerless        [C#]          AWS/Lambda/Serverless
Console Application                  console                       [C#], F#      Common/Console
Class library                        classlib                      [C#], F#      Common/Library
Unit Test Project                    mstest                        [C#], F#      Test/MSTest
xUnit Test Project                   xunit                         [C#], F#      Test/xUnit
ASP.NET Core Empty                   web                           [C#]          Web/Empty
ASP.NET Core Web App                 mvc                           [C#], F#      Web/MVC
ASP.NET Core Web API                 webapi                        [C#]          Web/WebAPI
Nuget Config                         nugetconfig                                 Config
Web Config                           webconfig                                   Config
Solution File                        sln                                         Solution
</code></pre>

To get help on a project template with `dotnet new` run the following:

`dotnet new lambda.EmptyFunction.Powertools --help`

```
Template Instantiation Commands for .NET Core CLI.

Usage: dotnet new [arguments] [options]

Arguments:
  template  The template to instantiate.

Options:
  -l|--list         List templates containing the specified name.
  -lang|--language  Specifies the language of the template to create
  -n|--name         The name for the output being created. If no name is specified, the name of the current directory is used.
  -o|--output       Location to place the generated output.
  -h|--help         Displays help for this command.
  -all|--show-all   Shows all templates


Lambda Empty Function with Lambda Powertools (C#)
Author: AWS
Options:
  -p|--profile  The AWS credentials profile set in aws-lambda-tools-defaults.json and used as the default profile when interacting with AWS.
                string - Optional

  -r|--region   The AWS region set in aws-lambda-tools-defaults.json and used as the default region when interacting with AWS.
                string - Optional
```

To create a project run the following command:

```
dotnet new lambda.EmptyFunction.Powertools --name ExampleFunction --profile default --region us-east-2
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-dotnet/tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by sliedig** [comment]
Template should also be available via the AWS Toolkit for Visual Studio IDE project template selection

![image](https://user-images.githubusercontent.com/597073/217533797-e509f32f-f505-4b9e-8d67-999581dbba28.png)

**Comment by normj** [comment]
I would recommend having a `Lambda Empty Function Powertools` and `Lambda Empty Serverless Powertools` blueprints. If you add one for a specific event type we will get into combinator problem as expectations would be to keep adding mirror versions for each event type.
