### ISSUE TITLE
Feature request: RemoveAllKeys feature

### ISSUE THREAD

**Issue by ssathasivanACR** [awslabs/aws-lambda-powertools-dotnet#288]
### Use case

We are currently integrating .NET Power Tools for Lambda - Logging in our asp.net web api based Lambda. We are appending some custom keys for application logs using the Logger.AppendKeys method. The current implementation of the RemoveKeys method expects a list of keys to be provided.

   ` //
        // Summary:
        //     Remove additional keys from the log context.
        //
        // Parameters:
        //   keys:
        //     The list of keys.
        public static void RemoveKeys(params string[] keys)
        {
            if (keys == null)
            {
                return;
            }

            foreach (string key in keys)
            {
                if (_scope.ContainsKey(key))
                {
                    _scope.Remove(key);
                }
            }
        }
`

### Solution/User Experience

It would be good if you can provide a RemoveAll Keys methods that can clear all the custom keys . There seems to be method: RemoveAllKeys but it is intenal

 //
        // Summary:
        //     Removes all additional keys from the log context.
        internal static void RemoveAllKeys()
        {
            _scope.Clear();
        }

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (.NET) Tenets](https://awslabs.github.io/aws-lambda-powertools-dotnet/tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by hjgraca** [comment]
@ssathasivanACR thanks for raising this feature request. 
There is a method to clear all keys between requests [ClearState = true](https://awslabs.github.io/aws-lambda-powertools-dotnet/core/logging/#clearing-all-state) essentially does a clear all between requests.
Would that work?

**Comment by ssathasivanACR** [comment]
My use case was satisfied with the Extra Keys feature.  The keys through Appendkeys were persisting in the subsequent logs within the same request. Took a little time to understand the documentation. A example of Extra Keys would be helpful

**Comment by hjgraca** [comment]
> My use case was satisfied with the Extra Keys feature.  The keys through Appendkeys were persisting in the subsequent logs within the same request. Took a little time to understand the documentation. A example of Extra Keys would be helpful

@ssathasivanACR Thanks for the feedback.
We are always looking into ways to improve our documentation and codebase. Could you share what was confusing so we can improve it? Thank you for using Powertools 🚀

**Comment by ssathasivanACR** [comment]
A code snippet would be useful
