### ISSUE TITLE
Feature request: Allow the default Service dimension to be removed from the Dimensions dictionary

### ISSUE THREAD

**Issue by glynn1211** [awslabs/aws-lambda-powertools-dotnet#292]
### Use case

I'm implementing this into my code for metrics as a clean and more efficent way of creating metrics, however I have hit a snag where I can't remove the Service Default Dimension even when using the Set Deafult Dimensions method. And would like to be able to use the existing metrics linked to alarms, without having to update them all to now be in the Service Dimension.

This would allow a user to have only the Dimensions they provide used by the metrics.

### Solution/User Experience

I have Identified that when calling the SetDefaultDimensions it has a check for !DeafultDimensions.Any() to see if it should just replace the existing DefaultDimensions otherwise just add the new set being passed in. You however on initialisation create the MetricContext with the DefaultDimensions already set thus stopping it from ever using just a custom set of dimensions.

Can be solved by either not initialising on context creation or by changing the Any check in SetDefaultDimensions. Another possible solution would be to be able to clear the existing DefaultDimensions so that when Set or Add is called they can populate with just the chosen Dimensions

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (.NET) Tenets](https://awslabs.github.io/aws-lambda-powertools-dotnet/tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by hjgraca** [comment]
Hi @glynn1211 thanks for raising this issue. 
We will look into it and get back to you as soon as possible. 
Thank you.

**Comment by glynn1211** [comment]
Hi, 
I have a PR for this, as I had the time. I went with the Clear method as this way I didn't touch on any of the exisiting code, hopeuflly this is alright. Let me know if I've done anything wrong and I'll do my best to correct it.

**Comment by hjgraca** [comment]
I was going to suggest a `ClearMethod` as well.

In Powertools Python the `ClearMehod` exists as shown in the [docs](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/metrics/metrics.py#LL113C1-L113C1) and [code](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/metrics/metrics.py#LL113C1-L113C1)

What I would suggest, instead of `ClearAllDimensions` rename it to `ClearDefaultDimentions`. This will make it the same name as we do in Python Powertools.
